/* Generated automatically by the program `gencodes'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CODES_H
#define GCC_INSN_CODES_H

enum insn_code {
  CODE_FOR_addsi3 = 0,
  CODE_FOR_subsi3 = 1,
  CODE_FOR_andsi3 = 2,
  CODE_FOR_iorsi3 = 3,
  CODE_FOR_xorsi3 = 4,
  CODE_FOR_nandsi3 = 5,
  CODE_FOR_norsi3 = 6,
  CODE_FOR_negsi2 = 7,
  CODE_FOR_one_cmplqi2 = 8,
  CODE_FOR_one_cmplhi2 = 9,
  CODE_FOR_one_cmplsi2 = 10,
  CODE_FOR_ashlsi3 = 11,
  CODE_FOR_ashrsi3 = 12,
  CODE_FOR_lshrsi3 = 13,
  CODE_FOR_mulsi3 = 14,
  CODE_FOR_divsi3 = 15,
  CODE_FOR_udivsi3 = 16,
  CODE_FOR_modsi3 = 17,
  CODE_FOR_umodsi3 = 18,
  CODE_FOR_truncsihi2 = 19,
  CODE_FOR_truncsiqi2 = 20,
  CODE_FOR_trunchiqi2 = 21,
  CODE_FOR_zero_extendqihi2 = 22,
  CODE_FOR_zero_extendhisi2 = 23,
  CODE_FOR_zero_extendqisi2 = 24,
  CODE_FOR_extendqisi2 = 25,
  CODE_FOR_extendhisi2 = 26,
  CODE_FOR_extendqihi2 = 27,
  CODE_FOR_movsi_general = 28,
  CODE_FOR_movhi_general = 29,
  CODE_FOR_movqi_general = 30,
  CODE_FOR_movsf_general = 31,
  CODE_FOR_movdf_general = 32,
  CODE_FOR_nop = 33,
  CODE_FOR_indirect_jump = 34,
  CODE_FOR_jump = 35,
  CODE_FOR_call_value = 36,
  CODE_FOR_call = 37,
  CODE_FOR_call_value_indirect = 38,
  CODE_FOR_call_indirect = 39,
  CODE_FOR_call_val_internal_return_r4 = 40,
  CODE_FOR_call_val_internal_return_r4_halfword = 41,
  CODE_FOR_call_val_internal_return_r4_quarterword = 42,
  CODE_FOR_call_val_internal_no_return = 43,
  CODE_FOR_tablejump = 44,
  CODE_FOR_int_cond_branch = 45,
  CODE_FOR_int_cond_branch_rev = 46,
  CODE_FOR_int_cond_branch_lt = 47,
  CODE_FOR_int_cond_branch_gt = 48,
  CODE_FOR_int_cond_branch_le = 49,
  CODE_FOR_int_cond_branch_ge = 50,
  CODE_FOR_int_cond_branch_ltu = 51,
  CODE_FOR_int_cond_branch_gtu = 52,
  CODE_FOR_int_cond_branch_leu = 53,
  CODE_FOR_int_cond_branch_geu = 54,
  CODE_FOR_set_internal = 55,
  CODE_FOR_movsi = 56,
  CODE_FOR_movhi = 57,
  CODE_FOR_movqi = 58,
  CODE_FOR_movsf = 59,
  CODE_FOR_cmpsi = 60,
  CODE_FOR_tstsi = 61,
  CODE_FOR_beq = 62,
  CODE_FOR_bne = 63,
  CODE_FOR_blt = 64,
  CODE_FOR_bgt = 65,
  CODE_FOR_ble = 66,
  CODE_FOR_bge = 67,
  CODE_FOR_bltu = 68,
  CODE_FOR_bgtu = 69,
  CODE_FOR_bleu = 70,
  CODE_FOR_bgeu = 71,
  CODE_FOR_eeq = 72,
  CODE_FOR_eneq = 73,
  CODE_FOR_elt = 74,
  CODE_FOR_eltu = 75,
  CODE_FOR_nothing
};

#endif /* GCC_INSN_CODES_H */
