/* This file is is generated by a shell script.  DO NOT EDIT! */

/* emulate the original gld for the given elf32_brownie32
   Copyright 1991, 1992, 1994, 1996, 1999, 2000, 2001, 2002, 2003, 2004
   Free Software Foundation, Inc.
   Written by Steve Chamberlain steve@cygnus.com

This file is part of GLD, the Gnu Linker.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */

#define TARGET_IS_elf32_brownie32

#include "bfd.h"
#include "sysdep.h"
#include "bfdlink.h"

#include "ld.h"
#include "ldmain.h"
#include "ldmisc.h"

#include "ldexp.h"
#include "ldlang.h"
#include "ldfile.h"
#include "ldemul.h"


static void
gldelf32_brownie32_before_parse (void)
{
#ifndef TARGET_			/* I.e., if not generic.  */
  ldfile_set_output_arch ("brownie32", bfd_arch_unknown);
#endif /* not TARGET_ */
}


static char *
gldelf32_brownie32_get_script (int *isfile)
{
  *isfile = 0;

  if (link_info.relocatable && config.build_constructors)
    return
"/* Script for ld -Ur: link w/out relocation, do create constructors */\n\
OUTPUT_FORMAT(\"elf32-brownie32\", \"\",\n\
	      \"\")\n\
OUTPUT_ARCH(brownie32)\n\
SECTIONS\n\
{\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
  }\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
  }\n\
  .bss :\n\
  {\n\
   *(.bss)\n\
   *(COMMON)\n\
   ;\n\
  }\n\
}\n\n"
  ; else if (link_info.relocatable) return
"/* Script for ld -r: link without relocation */\n\
OUTPUT_FORMAT(\"elf32-brownie32\", \"\",\n\
	      \"\")\n\
OUTPUT_ARCH(brownie32)\n\
SECTIONS\n\
{\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
  }\n\
  .data :\n\
  {\n\
    *(.data)\n\
  }\n\
  .bss :\n\
  {\n\
   *(.bss)\n\
   *(COMMON)\n\
   ;\n\
  }\n\
}\n\n"
  ; else if (!config.text_read_only) return
"/* Script for -N: mix text and data on same page; don't align data */\n\
OUTPUT_FORMAT(\"elf32-brownie32\", \"\",\n\
	      \"\")\n\
OUTPUT_ARCH(brownie32)\n\
SEARCH_DIR(\"/home/asip-sajjad04/ASIPSS20/ASIPMeisterProjects/Session0/brownie/meister/browstd32.swgen/brownie32-elf/lib\");\n\
SECTIONS\n\
{\n\
  . = 0x10000000;\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
    etext = .;\n\
  }\n\
  . = .;\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
    edata  =  .;\n\
  }\n\
  .bss :\n\
  {\n\
   *(.bss)\n\
   *(COMMON)\n"
"   end = . ;\n\
  }\n\
}\n\n"
  ; else if (!config.magic_demand_paged) return
"/* Script for -n: mix text and data on same page */\n\
OUTPUT_FORMAT(\"elf32-brownie32\", \"\",\n\
	      \"\")\n\
OUTPUT_ARCH(brownie32)\n\
SEARCH_DIR(\"/home/asip-sajjad04/ASIPSS20/ASIPMeisterProjects/Session0/brownie/meister/browstd32.swgen/brownie32-elf/lib\");\n\
SECTIONS\n\
{\n\
  . = 0x10000000;\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
    etext = ALIGN(1);\n\
  }\n\
  . = ALIGN(1);\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
    edata  =  .;\n\
  }\n\
  .bss :\n\
  {\n\
   *(.bss)\n\
   *(COMMON)\n"
"   end = . ;\n\
  }\n\
}\n\n"
  ; else return
"/* Default linker script, for normal executables */\n\
OUTPUT_FORMAT(\"elf32-brownie32\", \"\",\n\
	      \"\")\n\
OUTPUT_ARCH(brownie32)\n\
SEARCH_DIR(\"/home/asip-sajjad04/ASIPSS20/ASIPMeisterProjects/Session0/brownie/meister/browstd32.swgen/brownie32-elf/lib\");\n\
SECTIONS\n\
{\n\
  . = 0x10000000;\n\
  .text :\n\
  {\n\
    CREATE_OBJECT_SYMBOLS\n\
    *(.text)\n\
    etext = ALIGN(1);\n\
  }\n\
  . = ALIGN(1);\n\
  .data :\n\
  {\n\
    *(.data)\n\
    CONSTRUCTORS\n\
    edata  =  .;\n\
  }\n\
  .bss :\n\
  {\n\
   *(.bss)\n\
   *(COMMON)\n"
"   end = . ;\n\
  }\n\
}\n\n"
; }

struct ld_emulation_xfer_struct ld_elf32_brownie32_emulation =
{
  gldelf32_brownie32_before_parse,
  syslib_default,
  hll_default,
  after_parse_default,
  after_open_default,
  after_allocation_default,
  set_output_arch_default,
  ldemul_default_target,
  before_allocation_default,
  gldelf32_brownie32_get_script,
  "elf32_brownie32",
  "elf32-brownie32",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,	/* add_options */
  NULL,	/* handle_option */
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
};
