#!/bin/bash

test -r ../../env_settings || {
  echo
  echo "ERROR: \"env_settings\" could not be found!"
  echo "       Make sure, that you start this script from a subfolder"
  echo "       of the Assembly folder."
  echo
  exit 1
}



source ../../env_settings
APPLICATION_NAME=${PWD##*/} # everything after the last slash of the working directory
SCRIPT_FILE=script.txt
export COMPILER_TEMP_DIR=`pwd`/compiler_temp  # TODO: Should find out the real temp dir
#echo ---
#echo $COMPILER_TEMP_DIR
#echo ---



rm -f ${APPLICATION_NAME}.s


#$MKIMG_DIR/mkall


$MKIMG_DIR/mkall $* || {
	echo
	echo "ERROR: ABORTING \"mkallNOP\", BECAUSE \"mkall\" RETURNED AN ERROR !!"
	echo
	exit 1
    }    


$MKIMG_DIR/convert2PD1.pl ${COMPILER_TEMP_DIR}/${APPLICATION_NAME}.asm > ${APPLICATION_NAME}.s || {
	echo
	echo "ERROR: ABORTING \"mkallNOP\", BECAUSE \"convert2PD1\" RETURNED AN ERROR !!"
	echo
	exit 1
    }


../mkimg_fromS_remotePas ${APPLICATION_NAME}.s || {
	echo
	echo "ERROR: ABORTING \"mkallNOP\", BECAUSE \"mkimg_fromS_remotePas\" RETURNED AN ERROR !!"
	echo
	exit 1
   }    

#cp ${APPLICATION_NAME}.s ${APPLICATION_NAME}.dlxsim

echo "go" > $SCRIPT_FILE
echo "exit" >> $SCRIPT_FILE

../dlxsim -f${APPLICATION_NAME}.dlxsim -pd1 -da0 -sf${SCRIPT_FILE} -pfoutput.txt
cat output.txt

rm $SCRIPT_FILE
rm ${APPLICATION_NAME}.s
