#!/bin/bash

ASIPPROJ=dlx_basis

ASIPDIR=~/ASIP_CPUs/dlx_basis
ASIPPROJDIR=${ASIPDIR}/meister

COMPDIR=~/compdir
DEVREP=~/devrep
MEISTERCG=testcg
MEISTERCC=testcc

NEWCG=${DEVREP}/$1
NEWCC=${DEVREP}/$2

BUILDTREE=~/cosybuild
COMPFILE=${BUILDTREE}/components

#copy components file to buildtree
#cp -r ${COMPDIR}/components ${BUILDTREE}

#change names in components file
#sed s/${MEISTERCG}/$1/ ${COMPFILE} > ${COMPFILE}/tmp_comp
#sed s/${MEISTERCC}/$2/ ${COMPFILE/tmp_comp > ${BUILDTREE}/components

#switch to build dir and execute create build tree
#cd ${BUILDTREE}
#product extract

#use meistercg on SW-Tools files
cd ${ASIPPROJDIR}/${ASIPPROJ}.sw 
pwd
